export const slugTop10Product = {
  "top-10-laptop-ban-chay": { category: "Laptop" },
  "top-10-laptop-gaming-ban-chay": { category: "Laptop Gaming" },
  "top-10-pc-ban-chay": { category: "PC GVN" },
  "top-10-man-hinh-ban-chay": { category: "Màn hình" },
  "top-10-ban-phim-ban-chay": { category: "Bàn phím" },
  "top-10-chuot-ban-chay": { category: "Chuột" },
  "top-10-tai-nghe-ban-chay": { category: "Tai nghe" }
}

export const slugConditionMap = {
  "top-10-laptop-ban-chay": { category: "Laptop" },
  "top-10-laptop-gaming-ban-chay": { category: "Laptop Gaming" },
  "top-10-pc-ban-chay": { category: "PC GVN" },
  "top-10-man-hinh-ban-chay": { category: "Màn hình" },
  "top-10-ban-phim-ban-chay": { category: "Bàn phím" },
  "top-10-chuot-ban-chay": { category: "Chuột" },
  "top-10-tai-nghe-ban-chay": { category: "Tai nghe" },

  laptop: { category: "Laptop" },
  "laptop-asus-hoc-tap-va-lam-viec": { brand: "ASUS", category: "Laptop" },
  "laptop-acer-hoc-tap-va-lam-viec": { brand: "ACER", category: "Laptop" },
  "laptop-msi-hoc-tap-va-lam-viec": { brand: "MSI", category: "Laptop" },
  "laptop-lenovo-hoc-tap-va-lam-viec": { brand: "LENOVO", category: "Laptop" },
  "laptop-duoi-15-trieu": { price: { $lt: 15000000 }, category: "Laptop" },
  "laptop-tu-15-den-20-trieu": { price: { $gte: 15000000, $lt: 20000000 }, category: "Laptop" },
  "laptop-tren-20-trieu": { price: { $gte: 20000000 }, category: "Laptop" },

  "laptop-gaming": { category: "Laptop Gaming" },
  "laptop-gaming-asus": { category: "Laptop Gaming", brand: "ASUS" },
  "laptop-gaming-acer": { category: "Laptop Gaming", brand: "ACER" },
  "laptop-gaming-msi": { category: "Laptop Gaming", brand: "MSI" },
  "laptop-gaming-lenovo": { category: "Laptop Gaming", brand: "LENOVO" },
  "laptop-gaming-duoi-20-trieu": { price: { $lt: 20000000 }, category: "Laptop Gaming" },
  "laptop-gaming-tu-20-den-25-trieu": { price: { $gte: 20000000, $lt: 25000000 }, category: "Laptop Gaming" },
  "laptop-gaming-tren-25-trieu": { price: { $gte: 25000000 }, category: "Laptop Gaming" },

  "pc-gvn": { category: "PC GVN" },
  "pc-gvn-rtx-5090": { category: "PC GVN", brand: "GVN" },
  "pc-gvn-rtx-5080": { category: "PC GVN", brand: "GVN" },
  "pc-gvn-rtx-5070Ti": { category: "PC GVN", brand: "GVN" },
  "pc-gvn-rtx-5060Ti": { category: "PC GVN", brand: "GVN" },
  "pc-gvn-rtx-5060": { category: "PC GVN", brand: "GVN" },
  "pc-gvn-rtx-4060": { category: "PC GVN", brand: "GVN" },
  "pc-gvn-rtx-3060": { category: "PC GVN", brand: "GVN" },

  "man-hinh": { category: "Màn hình" },
  "man-hinh-samsung": { category: "Màn hình", brand: "SAMSUNG" },
  "man-hinh-asus": { category: "Màn hình", brand: "ASUS" },
  "man-hinh-dell": { category: "Màn hình", brand: "DELL" },
  "man-hinh-viewsonic": { category: "Màn hình", brand: "VIEWSONIC" },
  "man-hinh-acer": { category: "Màn hình", brand: "ACER" },
  "man-hinh-lg": { category: "Màn hình", brand: "LG" },
  "man-hinh-duoi-5-trieu": { price: { $lt: 5000000 }, category: "Màn hình" },
  "man-hinh-tu-5-den-10-trieu": { price: { $gte: 5000000, $lt: 10000000 }, category: "Màn hình" },
  "man-hinh-tu-10-den-20-trieu": { price: { $gte: 10000000, $lt: 20000000 }, category: "Màn hình" },
  "man-hinh-tren-20-trieu": { price: { $gte: 20000000 }, category: "Màn hình" },

  "ban-phim": { category: "Bàn phím" },
  "ban-phim-akko": { category: "Bàn phím", brand: "AKKO" },
  "ban-phim-aula": { category: "Bàn phím", brand: "AULA" },
  "ban-phim-dareu": { category: "Bàn phím", brand: "DARE-U" },
  "ban-phim-keychron": { category: "Bàn phím", brand: "KEYCHRON" },
  "ban-phim-corsair": { category: "Bàn phím", brand: "CORSAIR" },
  "ban-phim-asus": { category: "Bàn phím", brand: "ASUS" },
  "ban-phim-logitech": { category: "Bàn phím", brand: "LOGITECH" },
  "ban-phim-razer": { category: "Bàn phím", brand: "RAZER" },
  "ban-phim-duoi-1-trieu": { price: { $lt: 1000000 }, category: "Bàn phím" },
  "ban-phim-tu-1-den-2-trieu": { price: { $gte: 1000000, $lt: 2000000 }, category: "Bàn phím" },
  "ban-phim-tu-2-den-3-trieu": { price: { $gte: 2000000, $lt: 3000000 }, category: "Bàn phím" },
  "ban-phim-tren-3-trieu": { price: { $gte: 3000000 }, category: "Bàn phím" },

  chuot: { category: "Chuột" },
  "chuot-dareu": { category: "Chuột", brand: "DARE-U" },
  "chuot-corsair": { category: "Chuột", brand: "CORSAIR" },
  "chuot-asus": { category: "Chuột", brand: "ASUS" },
  "chuot-logitech": { category: "Chuột", brand: "LOGITECH" },
  "chuot-razer": { category: "Chuột", brand: "RAZER" },
  "chuot-duoi-1-trieu": { price: { $lt: 1000000 }, category: "Chuột" },
  "chuot-tu-1-den-3-trieu": { price: { $gte: 1000000, $lt: 3000000 }, category: "Chuột" },
  "chuot-tren-3-trieu": { price: { $gte: 3000000 }, category: "Chuột" },

  "tai-nghe": { category: "Tai nghe" },
  "tai-nghe-asus": { category: "Tai nghe", brand: "ASUS" },
  "tai-nghe-razer": { category: "Tai nghe", brand: "RAZER" },
  "tai-nghe-edifier": { category: "Tai nghe", brand: "Edifier" },
  "tai-nghe-logitech": { category: "Tai nghe", brand: "LOGITECH" },
  "tai-nghe-steelseries": { category: "Tai nghe", brand: "Steelseries" },
  "tai-nghe-duoi-1-trieu": { price: { $lt: 1000000 }, category: "Tai nghe" },
  "tai-nghe-tu-1-den-3-trieu": { price: { $gte: 1000000, $lt: 3000000 }, category: "Tai nghe" },
  "tai-nghe-tren-3-trieu": { price: { $gte: 3000000 }, category: "Tai nghe" },
  "tai-nghe-wireless": { category: "Tai nghe", other: "Wireless" },
  "tai-nghe-bluetooth": { category: "Tai nghe", other: "Bluetooth" },
  "tai-nghe-over-ear": { category: "Tai nghe", other: "Over-ear" },

  "ram-8gb": { category: "RAM, SSD, HDD", capacity_ram: "8GB" },
  "ram-16gb": { category: "RAM, SSD, HDD", capacity_ram: "16GB" },
  "ram-32gb": { category: "RAM, SSD, HDD", capacity_ram: "32GB" },
  "ram-64gb": { category: "RAM, SSD, HDD", capacity_ram: "64GB" },
  "ram-ddr4": { category: "RAM, SSD, HDD", type_ram: "DDR4" },
  "ram-ddr5": { category: "RAM, SSD, HDD", type_ram: "DDR5" },
  "ram-corsair": { category: "RAM, SSD, HDD", brand: "CORSAIR" },
  "ram-kingston": { category: "RAM, SSD, HDD", brand: "KingSton" },
  "ram-gskill": { category: "RAM, SSD, HDD", brand: "G.Skill" },
  "ram-all-ram": { category: "RAM, SSD, HDD" },

  "hdd-1tb": { category: "HDD", capacity_hdd: "1TB" },
  "hdd-2tb": { category: "HDD", capacity_hdd: "2TB" },
  "hdd-tren-2tb": { category: "HDD", capacity_hdd: "larger than 2TB" },
  "hdd-wester-digital": { category: "HDD", brand: "WesterDigital" },
  "hdd-seagate": { category: "HDD", brand: "Seagate" },
  "hdd-all-brand": { category: "HDD" },

  "ssd-120-128-gb": { category: "SSD", capacity_sdd: "120-128GB" },
  "ssd-250-256-gb": { category: "SSD", capacity_sdd: "250-256GB" },
  "ssd-480-512-gb": { category: "SSD", capacity_sdd: "480-512GB" },
  "ssd-960-1-tb": { category: "SSD", capacity_sdd: "960-1TB" },
  "ssd-tren-2-tb": { category: "SSD", capacity_sdd: "larger than 2TB" },
  "ssd-samsung": { category: "SSD", brand: "SAMSUNG" },
  "ssd-kingston": { category: "SSD", brand: "KingSton" },
  "ssd-corsair": { category: "SSD", brand: "CORSAIR" },
  "ssd-pny": { category: "SSD", brand: "PNY" },
  "ssd-all-brand": { category: "SSD" },

  "loa-edifier": { category: "Loa", brand: "Edifier" },
  "loa-razer": { category: "Loa", brand: "RAZER" },
  "loa-soundmax": { category: "Loa", brand: "SoundMax" },
  "loa-logitech": { category: "Loa", brand: "LOGITECH" },
  "loa-vi-tinh": { category: "Loa", type_loudspeaker: "Vi tính" },
  "loa-bluetooth": { category: "Loa", type_loudspeaker: "Bluetooth" },
  "loa-soundbar": { category: "Loa", type_loudspeaker: "Soundbar" },
  "loa-mini": { category: "Loa", type_loudspeaker: "Mini" },
  "loa-duoi-1-trieu": { price: { $lt: 1000000 }, category: "Loa" },
  "loa-tu-1-den-3-trieu": { price: { $gte: 1000000, $lt: 3000000 }, category: "Loa" },
  "loa-tren-3-trieu": { price: { $gte: 3000000 }, category: "Loa" },
  loa: { category: "Loa" }
}
